dist: trusty
language: perl
perl:
  - "5.30"
  - "5.24"
  - "5.12"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda info -a
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION perl-biox-seq bwa samtools
  - source activate test-env
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgd-dev
    - libdb-dev

