dist: trusty
language: perl
perl:
  - "5.30"
  - "5.24"
  - "5.12"
os:
  - linux
install:
  - cpanm git://github.com/jvolkening/p5-BioX-Seq.git
  - cpanm --quiet --installdeps --notest .
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgd-dev
    - libdb-dev
    - bwa
    - samtools

